### ISSUE TITLE
Having configuration defined in code generates more requests.

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#355]
1. When you have resource types defined inside `web.config` you will get one `GetFolders` request for a resource type with no subfolders. When resource type has subfolders the number of requests wil be proportional to the sub level you want to load e.g. loading `1000px` in `Images/big/1000px` will generate 3 requests and loading `big` in  in `Images/big/1000px` will generate 2.
2. When you define resource types in code (e.g. `ConnectorConfig.cs`) you will get as many `GetFolders` request as there are resource types assuming that we are not trying to get to any subfolder in any resource type.  If you have 3 resource types defined, you will get 3 requests while having same configuration in `web.config` will generate only one.

**Comment by zaak** [comment]
After looking closer at this issue it came out that additional `GetFolders` requests were caused by enabled `lazyLoad` option, which is correct and expected behavior. As you can read [in the docs](https://docs.ckeditor.com/ckfinder/ckfinder3-net/configuration.html#configuration_options_resources).

> `lazyLoad` - If set to `true`, the `Init` command will not check if the resource type contains child folders. This option is especially useful for remote backends, as the `Init` command will be executed faster, and therefore CKFinder will start faster, too. It is recommended to set it to `true` for remote backends.

To avoid additional requests please simply disable this option for `resourceType` (it's disabled by default).
