### ISSUE TITLE
Copy function available on readOnly mode in config.php

### ISSUE THREAD

**Issue by plbeast** [ckfinder/ckfinder#417]
when select a file, a copy icon display and copy function available when I 
config as in config.php:
`$config['readOnly'] = true;`

![image](https://user-images.githubusercontent.com/3580686/76331935-b5e9dc00-632a-11ea-9e3b-679cd61665ef.png)

Any way, when i add 
`readOnly:true,`
while initiate ckfinder.

The copy icon disappered.

**Comment by zaak** [comment]
Hi @plbeast! [As you can see](https://ckeditor.com/docs/ckfinder/ckfinder3-php/configuration.html#configuration_options), there is no option like this available in the CKFinder's PHP connector configuration.
The [`readOnly`](https://ckeditor.com/docs/ckfinder/ckfinder3/#!/api/CKFinder.Config-cfg-readOnly) option you have mentioned applies to the JavaScript client-side only.
Please note that `readOnly` will only disable certain UI elements. In order to successfully block file uploads or modifications, you will need to adjust [ACL settings](https://ckeditor.com/docs/ckfinder/ckfinder3-php/configuration.html#configuration_options_accessControl) accordingly in the server-side configuration file.

If you don't mind, I'll close this issue.

**Comment by plbeast** [comment]
Hi&nbsp;Paweł,


When I config as:
$config['accessControl'][] = array(
&nbsp; &nbsp; 'role'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; =&gt; 'photoView',
&nbsp; &nbsp; 'resourceType'&nbsp; &nbsp; &nbsp; &nbsp; =&gt; 'Photo gallery',
&nbsp; &nbsp; 'folder'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; =&gt; '/',


&nbsp; &nbsp; 'FOLDER_VIEW'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;=&gt; true,
&nbsp; &nbsp; 'FOLDER_CREATE'&nbsp; &nbsp; &nbsp; &nbsp;=&gt; false,
&nbsp; &nbsp; 'FOLDER_RENAME'&nbsp; &nbsp; &nbsp; &nbsp;=&gt; false,
&nbsp; &nbsp; 'FOLDER_DELETE'&nbsp; &nbsp; &nbsp; &nbsp;=&gt; false,


&nbsp; &nbsp; 'FILE_VIEW'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;=&gt; true,
&nbsp; &nbsp; 'FILE_CREATE'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;=&gt; false,
&nbsp; &nbsp; 'FILE_RENAME'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;=&gt; false,
&nbsp; &nbsp; 'FILE_DELETE'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;=&gt; false,


&nbsp; &nbsp; 'IMAGE_RESIZE'&nbsp; &nbsp; &nbsp; &nbsp; =&gt; false,
&nbsp; &nbsp; 'IMAGE_RESIZE_CUSTOM' =&gt; false
);

&nbsp;But the copy button still appeared on the browser.&nbsp;

Any way, the function did not work.



I think it is not nessary to show the copy button while in this config.


BR


@plbeast!


------------------&nbsp;Original&nbsp;------------------
