### ISSUE TITLE
Resized image (via "Choose Resised" button) removed after click that image in the popup again.

### ISSUE THREAD

**Issue by dkovganko** [ckfinder/ckfinder#447]
The GetResizedImages command triggers IFileSystem.DeleteFolderAsync() method that delete resized image.

**Steps to reproduce:**
- Open the CkFinder popup and select the image
- Click the "Choose Resized" button
- Select "Custom" option, change size and click Ok.
- Open the CkFinder popup again.
In this moment resized image still exists (in __thumbs/[imageName] folder).
- Click the image (the original image that you resized before)

**Result:** the resized image was removed

I noticed that when I click the image, the GetResizedImages command is called, and that triggers IFileSystem.DeleteFolderAsync() method that deletes the folder with the resized image (__thumbs/[imageName]).

https://www.screencast.com/t/yqiopIMH

Is it the issue in the CkFinder or is there some setting that handles this?

**Comment by jswiderski** [comment]
We have tested described scenario, however, we weren't able to get any errors. All resized images were preserved as expected. Please make sure that you are using latest CKFinder version and that you haven't made any modifications which might influence the problem you are getting.

![](https://user-images.githubusercontent.com/5314687/98362407-75636f00-202d-11eb-88cf-3426aa999153.png)

**NOTE:** The `__thumbs` folder is hidden by default. In our opinion it is better to it more like a private CKFinder folder and not making it available in the UI because then any user can delete it unless you set appropriate Access Control (ACL) to prevent that.

```xml
// Default settings
<hideFolders>
      <folder name=".*" />
      <folder name="CVS" />
      <folder name="__thumbs" />
</hideFolders>
```
