### ISSUE TITLE
flysystem upgrade ?

### ISSUE THREAD

**Issue by treeindark** [ckfinder/ckfinder#487]
did you project to upgrade flysystem to v2 or v3 ?

**Comment by Kocal** [comment]
It would be a **great** enhancement to add support to Flysystem 2 and/or 3. 

It would allow us to install the CKFinder Bundle with Symfony 6, because there is a version conflict with dependency `psr/cache`, used by CKFinder and Symfony: 
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/2103975/159803512-27d381c8-5e1b-4317-aca7-76052b61c1b5.png">

**Comment by zaak** [comment]
Done. Flysystem has been upgraded to version 3 in CKFinder v3.6.0.
