### ISSUE TITLE
Import from Word (Cannot read properties of null (reading 'id'))

### ISSUE THREAD

**Issue by brankomilovanovic** [ckfinder/ckfinder#497]
Hello everyone, I want to add a new feature of inserting a Word document through CKEditor5, but I'm getting this error and I can't seem to find a solution anywhere. Any help would be greatly appreciated.

I am getting this error:
![Screenshot 2023-04-20 at 14 22 49](https://user-images.githubusercontent.com/87083680/233364991-4b3982f3-6853-4baf-9cea-363dc2db5d00.png)

These are my settings for importing a Word:

`importWord: {
    tokenUrl: 'MyToken',
    defaultStyles: true,
    commentsStyles: 'none'
}`

**Comment by zaak** [comment]
Hi @brankomilovanovic. Thanks for submitting your issue, but it appears that you might have accidentally posted it in the wrong repository. This repository is for CKFinder, a file manager, but it seems like your issue is related to CKEditor 5.

Please log your issue in the appropriate repository at https://github.com/ckeditor/ckeditor5/issues. That way, our team can quickly identify the problem and provide a solution.
